disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    
    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
    - force_cast
    
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    
    # 다중 클로저 구문을 사용할 때 후행 클로저 구문은 사용할 수 없습니다. https://realm.github.io/SwiftLint/trailing_closure.html
    - multiple_closures_with_trailing_closure

    # https://realm.github.io/SwiftLint/cyclomatic_complexity.html
    - cyclomatic_complexity
    
    # https://realm.github.io/SwiftLint/function_body_length.html
    - function_body_length

    # https://realm.github.io/SwiftLint/nesting.html
    -  nesting
