name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out project
      uses: actions/checkout@v3
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Build and Test
      run: xcodebuild test -project Planz.xcodeproj -scheme Planz -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
    - name: Test Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        details: Test Failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
